/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as PublishSuccessRouteImport } from './routes/publish.success'
import { Route as OnboardingThemeRouteImport } from './routes/onboarding.theme'
import { Route as OnboardingPrenomsRouteImport } from './routes/onboarding.prenoms'
import { Route as OnboardingEvenementRouteImport } from './routes/onboarding.evenement'
import { Route as OnboardingDatesRouteImport } from './routes/onboarding.dates'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DashboardVueRouteImport } from './routes/dashboard.vue'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as DashboardShareRouteImport } from './routes/dashboard.share'
import { Route as DashboardPreviewRouteImport } from './routes/dashboard.preview'
import { Route as DashboardLandingRouteImport } from './routes/dashboard.landing'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard.invites'
import { Route as DashboardCeremoniesRouteImport } from './routes/dashboard.ceremonies'
import { Route as DashboardGuestsIndexRouteImport } from './routes/dashboard.guests.index'
import { Route as DashboardGuestsNewRouteImport } from './routes/dashboard.guests.new'
import { Route as DashboardCeremoniesIdRouteImport } from './routes/dashboard.ceremonies.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const PublishSuccessRoute = PublishSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PublishRoute,
} as any)
const OnboardingThemeRoute = OnboardingThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPrenomsRoute = OnboardingPrenomsRouteImport.update({
  id: '/prenoms',
  path: '/prenoms',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingEvenementRoute = OnboardingEvenementRouteImport.update({
  id: '/evenement',
  path: '/evenement',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDatesRoute = OnboardingDatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => OnboardingRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVueRoute = DashboardVueRouteImport.update({
  id: '/vue',
  path: '/vue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShareRoute = DashboardShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreviewRoute = DashboardPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandingRoute = DashboardLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCeremoniesRoute = DashboardCeremoniesRouteImport.update({
  id: '/ceremonies',
  path: '/ceremonies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuestsIndexRoute = DashboardGuestsIndexRouteImport.update({
  id: '/guests/',
  path: '/guests/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuestsNewRoute = DashboardGuestsNewRouteImport.update({
  id: '/guests/new',
  path: '/guests/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCeremoniesIdRoute = DashboardCeremoniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCeremoniesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/publish': typeof PublishRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/ceremonies': typeof DashboardCeremoniesRouteWithChildren
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/vue': typeof DashboardVueRoute
  '/e/$slug': typeof ESlugRoute
  '/onboarding/dates': typeof OnboardingDatesRoute
  '/onboarding/evenement': typeof OnboardingEvenementRoute
  '/onboarding/prenoms': typeof OnboardingPrenomsRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/publish/success': typeof PublishSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ceremonies/$id': typeof DashboardCeremoniesIdRoute
  '/dashboard/guests/new': typeof DashboardGuestsNewRoute
  '/dashboard/guests/': typeof DashboardGuestsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/publish': typeof PublishRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/ceremonies': typeof DashboardCeremoniesRouteWithChildren
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/vue': typeof DashboardVueRoute
  '/e/$slug': typeof ESlugRoute
  '/onboarding/dates': typeof OnboardingDatesRoute
  '/onboarding/evenement': typeof OnboardingEvenementRoute
  '/onboarding/prenoms': typeof OnboardingPrenomsRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/publish/success': typeof PublishSuccessRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ceremonies/$id': typeof DashboardCeremoniesIdRoute
  '/dashboard/guests/new': typeof DashboardGuestsNewRoute
  '/dashboard/guests': typeof DashboardGuestsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/publish': typeof PublishRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/ceremonies': typeof DashboardCeremoniesRouteWithChildren
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/vue': typeof DashboardVueRoute
  '/e/$slug': typeof ESlugRoute
  '/onboarding/dates': typeof OnboardingDatesRoute
  '/onboarding/evenement': typeof OnboardingEvenementRoute
  '/onboarding/prenoms': typeof OnboardingPrenomsRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/publish/success': typeof PublishSuccessRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ceremonies/$id': typeof DashboardCeremoniesIdRoute
  '/dashboard/guests/new': typeof DashboardGuestsNewRoute
  '/dashboard/guests/': typeof DashboardGuestsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/publish'
    | '/signup'
    | '/dashboard/ceremonies'
    | '/dashboard/invites'
    | '/dashboard/landing'
    | '/dashboard/preview'
    | '/dashboard/share'
    | '/dashboard/stats'
    | '/dashboard/vue'
    | '/e/$slug'
    | '/onboarding/dates'
    | '/onboarding/evenement'
    | '/onboarding/prenoms'
    | '/onboarding/theme'
    | '/publish/success'
    | '/dashboard/'
    | '/dashboard/ceremonies/$id'
    | '/dashboard/guests/new'
    | '/dashboard/guests/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/publish'
    | '/signup'
    | '/dashboard/ceremonies'
    | '/dashboard/invites'
    | '/dashboard/landing'
    | '/dashboard/preview'
    | '/dashboard/share'
    | '/dashboard/stats'
    | '/dashboard/vue'
    | '/e/$slug'
    | '/onboarding/dates'
    | '/onboarding/evenement'
    | '/onboarding/prenoms'
    | '/onboarding/theme'
    | '/publish/success'
    | '/dashboard'
    | '/dashboard/ceremonies/$id'
    | '/dashboard/guests/new'
    | '/dashboard/guests'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/publish'
    | '/signup'
    | '/dashboard/ceremonies'
    | '/dashboard/invites'
    | '/dashboard/landing'
    | '/dashboard/preview'
    | '/dashboard/share'
    | '/dashboard/stats'
    | '/dashboard/vue'
    | '/e/$slug'
    | '/onboarding/dates'
    | '/onboarding/evenement'
    | '/onboarding/prenoms'
    | '/onboarding/theme'
    | '/publish/success'
    | '/dashboard/'
    | '/dashboard/ceremonies/$id'
    | '/dashboard/guests/new'
    | '/dashboard/guests/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  InvitationRoute: typeof InvitationRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PublishRoute: typeof PublishRouteWithChildren
  SignupRoute: typeof SignupRoute
  ESlugRoute: typeof ESlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/publish/success': {
      id: '/publish/success'
      path: '/success'
      fullPath: '/publish/success'
      preLoaderRoute: typeof PublishSuccessRouteImport
      parentRoute: typeof PublishRoute
    }
    '/onboarding/theme': {
      id: '/onboarding/theme'
      path: '/theme'
      fullPath: '/onboarding/theme'
      preLoaderRoute: typeof OnboardingThemeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/prenoms': {
      id: '/onboarding/prenoms'
      path: '/prenoms'
      fullPath: '/onboarding/prenoms'
      preLoaderRoute: typeof OnboardingPrenomsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/evenement': {
      id: '/onboarding/evenement'
      path: '/evenement'
      fullPath: '/onboarding/evenement'
      preLoaderRoute: typeof OnboardingEvenementRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/dates': {
      id: '/onboarding/dates'
      path: '/dates'
      fullPath: '/onboarding/dates'
      preLoaderRoute: typeof OnboardingDatesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vue': {
      id: '/dashboard/vue'
      path: '/vue'
      fullPath: '/dashboard/vue'
      preLoaderRoute: typeof DashboardVueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/share': {
      id: '/dashboard/share'
      path: '/share'
      fullPath: '/dashboard/share'
      preLoaderRoute: typeof DashboardShareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preview': {
      id: '/dashboard/preview'
      path: '/preview'
      fullPath: '/dashboard/preview'
      preLoaderRoute: typeof DashboardPreviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landing': {
      id: '/dashboard/landing'
      path: '/landing'
      fullPath: '/dashboard/landing'
      preLoaderRoute: typeof DashboardLandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ceremonies': {
      id: '/dashboard/ceremonies'
      path: '/ceremonies'
      fullPath: '/dashboard/ceremonies'
      preLoaderRoute: typeof DashboardCeremoniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guests/': {
      id: '/dashboard/guests/'
      path: '/guests'
      fullPath: '/dashboard/guests/'
      preLoaderRoute: typeof DashboardGuestsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guests/new': {
      id: '/dashboard/guests/new'
      path: '/guests/new'
      fullPath: '/dashboard/guests/new'
      preLoaderRoute: typeof DashboardGuestsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ceremonies/$id': {
      id: '/dashboard/ceremonies/$id'
      path: '/$id'
      fullPath: '/dashboard/ceremonies/$id'
      preLoaderRoute: typeof DashboardCeremoniesIdRouteImport
      parentRoute: typeof DashboardCeremoniesRoute
    }
  }
}

interface DashboardCeremoniesRouteChildren {
  DashboardCeremoniesIdRoute: typeof DashboardCeremoniesIdRoute
}

const DashboardCeremoniesRouteChildren: DashboardCeremoniesRouteChildren = {
  DashboardCeremoniesIdRoute: DashboardCeremoniesIdRoute,
}

const DashboardCeremoniesRouteWithChildren =
  DashboardCeremoniesRoute._addFileChildren(DashboardCeremoniesRouteChildren)

interface DashboardRouteChildren {
  DashboardCeremoniesRoute: typeof DashboardCeremoniesRouteWithChildren
  DashboardInvitesRoute: typeof DashboardInvitesRoute
  DashboardLandingRoute: typeof DashboardLandingRoute
  DashboardPreviewRoute: typeof DashboardPreviewRoute
  DashboardShareRoute: typeof DashboardShareRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardVueRoute: typeof DashboardVueRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuestsNewRoute: typeof DashboardGuestsNewRoute
  DashboardGuestsIndexRoute: typeof DashboardGuestsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardCeremoniesRoute: DashboardCeremoniesRouteWithChildren,
  DashboardInvitesRoute: DashboardInvitesRoute,
  DashboardLandingRoute: DashboardLandingRoute,
  DashboardPreviewRoute: DashboardPreviewRoute,
  DashboardShareRoute: DashboardShareRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardVueRoute: DashboardVueRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuestsNewRoute: DashboardGuestsNewRoute,
  DashboardGuestsIndexRoute: DashboardGuestsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingDatesRoute: typeof OnboardingDatesRoute
  OnboardingEvenementRoute: typeof OnboardingEvenementRoute
  OnboardingPrenomsRoute: typeof OnboardingPrenomsRoute
  OnboardingThemeRoute: typeof OnboardingThemeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingDatesRoute: OnboardingDatesRoute,
  OnboardingEvenementRoute: OnboardingEvenementRoute,
  OnboardingPrenomsRoute: OnboardingPrenomsRoute,
  OnboardingThemeRoute: OnboardingThemeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PublishRouteChildren {
  PublishSuccessRoute: typeof PublishSuccessRoute
}

const PublishRouteChildren: PublishRouteChildren = {
  PublishSuccessRoute: PublishSuccessRoute,
}

const PublishRouteWithChildren =
  PublishRoute._addFileChildren(PublishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRouteWithChildren,
  InvitationRoute: InvitationRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PublishRoute: PublishRouteWithChildren,
  SignupRoute: SignupRoute,
  ESlugRoute: ESlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
