/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermesEtConditionsRouteImport } from './routes/termes-et-conditions'
import { Route as TemoignagesRouteImport } from './routes/temoignages'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PublishRouteImport } from './routes/publish'
import { Route as PolitiqueDeConfidentialiteRouteImport } from './routes/politique-de-confidentialite'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as InvitationRouteImport } from './routes/invitation'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CommentCaMarcheRouteImport } from './routes/comment-ca-marche'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as ThemeThumbSlugRouteImport } from './routes/theme-thumb.$slug'
import { Route as PublishSuccessRouteImport } from './routes/publish.success'
import { Route as OnboardingThemeRouteImport } from './routes/onboarding.theme'
import { Route as OnboardingPrenomsRouteImport } from './routes/onboarding.prenoms'
import { Route as OnboardingEvenementRouteImport } from './routes/onboarding.evenement'
import { Route as OnboardingDatesRouteImport } from './routes/onboarding.dates'
import { Route as ESlugRouteImport } from './routes/e.$slug'
import { Route as DashboardVueRouteImport } from './routes/dashboard.vue'
import { Route as DashboardStatsRouteImport } from './routes/dashboard.stats'
import { Route as DashboardShareRouteImport } from './routes/dashboard.share'
import { Route as DashboardPreviewRouteImport } from './routes/dashboard.preview'
import { Route as DashboardLandingRouteImport } from './routes/dashboard.landing'
import { Route as DashboardInvitesRouteImport } from './routes/dashboard.invites'
import { Route as DashboardEventsRouteImport } from './routes/dashboard.events'
import { Route as DashboardCeremoniesRouteImport } from './routes/dashboard.ceremonies'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AdminWeddingsRouteImport } from './routes/admin.weddings'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminEmailsRouteImport } from './routes/admin.emails'
import { Route as AdminActivityRouteImport } from './routes/admin.activity'
import { Route as DashboardGuestsIndexRouteImport } from './routes/dashboard.guests.index'
import { Route as DashboardGuestsNewRouteImport } from './routes/dashboard.guests.new'
import { Route as DashboardCeremoniesIdRouteImport } from './routes/dashboard.ceremonies.$id'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicWebhooksPaystackRouteImport } from './routes/api/public/webhooks/paystack'

const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermesEtConditionsRoute = TermesEtConditionsRouteImport.update({
  id: '/termes-et-conditions',
  path: '/termes-et-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const TemoignagesRoute = TemoignagesRouteImport.update({
  id: '/temoignages',
  path: '/temoignages',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishRoute = PublishRouteImport.update({
  id: '/publish',
  path: '/publish',
  getParentRoute: () => rootRouteImport,
} as any)
const PolitiqueDeConfidentialiteRoute =
  PolitiqueDeConfidentialiteRouteImport.update({
    id: '/politique-de-confidentialite',
    path: '/politique-de-confidentialite',
    getParentRoute: () => rootRouteImport,
  } as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const InvitationRoute = InvitationRouteImport.update({
  id: '/invitation',
  path: '/invitation',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CommentCaMarcheRoute = CommentCaMarcheRouteImport.update({
  id: '/comment-ca-marche',
  path: '/comment-ca-marche',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const ThemeThumbSlugRoute = ThemeThumbSlugRouteImport.update({
  id: '/theme-thumb/$slug',
  path: '/theme-thumb/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishSuccessRoute = PublishSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PublishRoute,
} as any)
const OnboardingThemeRoute = OnboardingThemeRouteImport.update({
  id: '/theme',
  path: '/theme',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingPrenomsRoute = OnboardingPrenomsRouteImport.update({
  id: '/prenoms',
  path: '/prenoms',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingEvenementRoute = OnboardingEvenementRouteImport.update({
  id: '/evenement',
  path: '/evenement',
  getParentRoute: () => OnboardingRoute,
} as any)
const OnboardingDatesRoute = OnboardingDatesRouteImport.update({
  id: '/dates',
  path: '/dates',
  getParentRoute: () => OnboardingRoute,
} as any)
const ESlugRoute = ESlugRouteImport.update({
  id: '/e/$slug',
  path: '/e/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardVueRoute = DashboardVueRouteImport.update({
  id: '/vue',
  path: '/vue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardStatsRoute = DashboardStatsRouteImport.update({
  id: '/stats',
  path: '/stats',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardShareRoute = DashboardShareRouteImport.update({
  id: '/share',
  path: '/share',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPreviewRoute = DashboardPreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardLandingRoute = DashboardLandingRouteImport.update({
  id: '/landing',
  path: '/landing',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInvitesRoute = DashboardInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardEventsRoute = DashboardEventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCeremoniesRoute = DashboardCeremoniesRouteImport.update({
  id: '/ceremonies',
  path: '/ceremonies',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => DashboardRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWeddingsRoute = AdminWeddingsRouteImport.update({
  id: '/weddings',
  path: '/weddings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEmailsRoute = AdminEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => AdminRoute,
} as any)
const AdminActivityRoute = AdminActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AdminRoute,
} as any)
const DashboardGuestsIndexRoute = DashboardGuestsIndexRouteImport.update({
  id: '/guests/',
  path: '/guests/',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardGuestsNewRoute = DashboardGuestsNewRouteImport.update({
  id: '/guests/new',
  path: '/guests/new',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardCeremoniesIdRoute = DashboardCeremoniesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => DashboardCeremoniesRoute,
} as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWebhooksPaystackRoute =
  ApiPublicWebhooksPaystackRouteImport.update({
    id: '/api/public/webhooks/paystack',
    path: '/api/public/webhooks/paystack',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/publish': typeof PublishRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/termes-et-conditions': typeof TermesEtConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/weddings': typeof AdminWeddingsRoute
  '/app/profile': typeof AppProfileRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/ceremonies': typeof DashboardCeremoniesRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/vue': typeof DashboardVueRoute
  '/e/$slug': typeof ESlugRoute
  '/onboarding/dates': typeof OnboardingDatesRoute
  '/onboarding/evenement': typeof OnboardingEvenementRoute
  '/onboarding/prenoms': typeof OnboardingPrenomsRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/publish/success': typeof PublishSuccessRoute
  '/theme-thumb/$slug': typeof ThemeThumbSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ceremonies/$id': typeof DashboardCeremoniesIdRoute
  '/dashboard/guests/new': typeof DashboardGuestsNewRoute
  '/dashboard/guests/': typeof DashboardGuestsIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/publish': typeof PublishRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/termes-et-conditions': typeof TermesEtConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/weddings': typeof AdminWeddingsRoute
  '/app/profile': typeof AppProfileRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/ceremonies': typeof DashboardCeremoniesRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/vue': typeof DashboardVueRoute
  '/e/$slug': typeof ESlugRoute
  '/onboarding/dates': typeof OnboardingDatesRoute
  '/onboarding/evenement': typeof OnboardingEvenementRoute
  '/onboarding/prenoms': typeof OnboardingPrenomsRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/publish/success': typeof PublishSuccessRoute
  '/theme-thumb/$slug': typeof ThemeThumbSlugRoute
  '/admin': typeof AdminIndexRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/ceremonies/$id': typeof DashboardCeremoniesIdRoute
  '/dashboard/guests/new': typeof DashboardGuestsNewRoute
  '/dashboard/guests': typeof DashboardGuestsIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/blog': typeof BlogRoute
  '/comment-ca-marche': typeof CommentCaMarcheRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/invitation': typeof InvitationRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRouteWithChildren
  '/politique-de-confidentialite': typeof PolitiqueDeConfidentialiteRoute
  '/publish': typeof PublishRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/temoignages': typeof TemoignagesRoute
  '/termes-et-conditions': typeof TermesEtConditionsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/admin/activity': typeof AdminActivityRoute
  '/admin/emails': typeof AdminEmailsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/weddings': typeof AdminWeddingsRoute
  '/app/profile': typeof AppProfileRoute
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/ceremonies': typeof DashboardCeremoniesRouteWithChildren
  '/dashboard/events': typeof DashboardEventsRoute
  '/dashboard/invites': typeof DashboardInvitesRoute
  '/dashboard/landing': typeof DashboardLandingRoute
  '/dashboard/preview': typeof DashboardPreviewRoute
  '/dashboard/share': typeof DashboardShareRoute
  '/dashboard/stats': typeof DashboardStatsRoute
  '/dashboard/vue': typeof DashboardVueRoute
  '/e/$slug': typeof ESlugRoute
  '/onboarding/dates': typeof OnboardingDatesRoute
  '/onboarding/evenement': typeof OnboardingEvenementRoute
  '/onboarding/prenoms': typeof OnboardingPrenomsRoute
  '/onboarding/theme': typeof OnboardingThemeRoute
  '/publish/success': typeof PublishSuccessRoute
  '/theme-thumb/$slug': typeof ThemeThumbSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/ceremonies/$id': typeof DashboardCeremoniesIdRoute
  '/dashboard/guests/new': typeof DashboardGuestsNewRoute
  '/dashboard/guests/': typeof DashboardGuestsIndexRoute
  '/api/public/webhooks/paystack': typeof ApiPublicWebhooksPaystackRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/blog'
    | '/comment-ca-marche'
    | '/dashboard'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/politique-de-confidentialite'
    | '/publish'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/temoignages'
    | '/termes-et-conditions'
    | '/verify-email'
    | '/admin/activity'
    | '/admin/emails'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/weddings'
    | '/app/profile'
    | '/dashboard/billing'
    | '/dashboard/ceremonies'
    | '/dashboard/events'
    | '/dashboard/invites'
    | '/dashboard/landing'
    | '/dashboard/preview'
    | '/dashboard/share'
    | '/dashboard/stats'
    | '/dashboard/vue'
    | '/e/$slug'
    | '/onboarding/dates'
    | '/onboarding/evenement'
    | '/onboarding/prenoms'
    | '/onboarding/theme'
    | '/publish/success'
    | '/theme-thumb/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/ceremonies/$id'
    | '/dashboard/guests/new'
    | '/dashboard/guests/'
    | '/api/public/webhooks/paystack'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/comment-ca-marche'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/politique-de-confidentialite'
    | '/publish'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/temoignages'
    | '/termes-et-conditions'
    | '/verify-email'
    | '/admin/activity'
    | '/admin/emails'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/weddings'
    | '/app/profile'
    | '/dashboard/billing'
    | '/dashboard/ceremonies'
    | '/dashboard/events'
    | '/dashboard/invites'
    | '/dashboard/landing'
    | '/dashboard/preview'
    | '/dashboard/share'
    | '/dashboard/stats'
    | '/dashboard/vue'
    | '/e/$slug'
    | '/onboarding/dates'
    | '/onboarding/evenement'
    | '/onboarding/prenoms'
    | '/onboarding/theme'
    | '/publish/success'
    | '/theme-thumb/$slug'
    | '/admin'
    | '/dashboard'
    | '/dashboard/ceremonies/$id'
    | '/dashboard/guests/new'
    | '/dashboard/guests'
    | '/api/public/webhooks/paystack'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/blog'
    | '/comment-ca-marche'
    | '/dashboard'
    | '/forgot-password'
    | '/invitation'
    | '/login'
    | '/onboarding'
    | '/politique-de-confidentialite'
    | '/publish'
    | '/reset-password'
    | '/signup'
    | '/sitemap.xml'
    | '/temoignages'
    | '/termes-et-conditions'
    | '/verify-email'
    | '/admin/activity'
    | '/admin/emails'
    | '/admin/login'
    | '/admin/payments'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/weddings'
    | '/app/profile'
    | '/dashboard/billing'
    | '/dashboard/ceremonies'
    | '/dashboard/events'
    | '/dashboard/invites'
    | '/dashboard/landing'
    | '/dashboard/preview'
    | '/dashboard/share'
    | '/dashboard/stats'
    | '/dashboard/vue'
    | '/e/$slug'
    | '/onboarding/dates'
    | '/onboarding/evenement'
    | '/onboarding/prenoms'
    | '/onboarding/theme'
    | '/publish/success'
    | '/theme-thumb/$slug'
    | '/admin/'
    | '/dashboard/'
    | '/dashboard/ceremonies/$id'
    | '/dashboard/guests/new'
    | '/dashboard/guests/'
    | '/api/public/webhooks/paystack'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BlogRoute: typeof BlogRoute
  CommentCaMarcheRoute: typeof CommentCaMarcheRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  InvitationRoute: typeof InvitationRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRouteWithChildren
  PolitiqueDeConfidentialiteRoute: typeof PolitiqueDeConfidentialiteRoute
  PublishRoute: typeof PublishRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TemoignagesRoute: typeof TemoignagesRoute
  TermesEtConditionsRoute: typeof TermesEtConditionsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  AppProfileRoute: typeof AppProfileRoute
  ESlugRoute: typeof ESlugRoute
  ThemeThumbSlugRoute: typeof ThemeThumbSlugRoute
  ApiPublicWebhooksPaystackRoute: typeof ApiPublicWebhooksPaystackRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termes-et-conditions': {
      id: '/termes-et-conditions'
      path: '/termes-et-conditions'
      fullPath: '/termes-et-conditions'
      preLoaderRoute: typeof TermesEtConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/temoignages': {
      id: '/temoignages'
      path: '/temoignages'
      fullPath: '/temoignages'
      preLoaderRoute: typeof TemoignagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish': {
      id: '/publish'
      path: '/publish'
      fullPath: '/publish'
      preLoaderRoute: typeof PublishRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politique-de-confidentialite': {
      id: '/politique-de-confidentialite'
      path: '/politique-de-confidentialite'
      fullPath: '/politique-de-confidentialite'
      preLoaderRoute: typeof PolitiqueDeConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invitation': {
      id: '/invitation'
      path: '/invitation'
      fullPath: '/invitation'
      preLoaderRoute: typeof InvitationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comment-ca-marche': {
      id: '/comment-ca-marche'
      path: '/comment-ca-marche'
      fullPath: '/comment-ca-marche'
      preLoaderRoute: typeof CommentCaMarcheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/theme-thumb/$slug': {
      id: '/theme-thumb/$slug'
      path: '/theme-thumb/$slug'
      fullPath: '/theme-thumb/$slug'
      preLoaderRoute: typeof ThemeThumbSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publish/success': {
      id: '/publish/success'
      path: '/success'
      fullPath: '/publish/success'
      preLoaderRoute: typeof PublishSuccessRouteImport
      parentRoute: typeof PublishRoute
    }
    '/onboarding/theme': {
      id: '/onboarding/theme'
      path: '/theme'
      fullPath: '/onboarding/theme'
      preLoaderRoute: typeof OnboardingThemeRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/prenoms': {
      id: '/onboarding/prenoms'
      path: '/prenoms'
      fullPath: '/onboarding/prenoms'
      preLoaderRoute: typeof OnboardingPrenomsRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/evenement': {
      id: '/onboarding/evenement'
      path: '/evenement'
      fullPath: '/onboarding/evenement'
      preLoaderRoute: typeof OnboardingEvenementRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/onboarding/dates': {
      id: '/onboarding/dates'
      path: '/dates'
      fullPath: '/onboarding/dates'
      preLoaderRoute: typeof OnboardingDatesRouteImport
      parentRoute: typeof OnboardingRoute
    }
    '/e/$slug': {
      id: '/e/$slug'
      path: '/e/$slug'
      fullPath: '/e/$slug'
      preLoaderRoute: typeof ESlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/vue': {
      id: '/dashboard/vue'
      path: '/vue'
      fullPath: '/dashboard/vue'
      preLoaderRoute: typeof DashboardVueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/stats': {
      id: '/dashboard/stats'
      path: '/stats'
      fullPath: '/dashboard/stats'
      preLoaderRoute: typeof DashboardStatsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/share': {
      id: '/dashboard/share'
      path: '/share'
      fullPath: '/dashboard/share'
      preLoaderRoute: typeof DashboardShareRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/preview': {
      id: '/dashboard/preview'
      path: '/preview'
      fullPath: '/dashboard/preview'
      preLoaderRoute: typeof DashboardPreviewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/landing': {
      id: '/dashboard/landing'
      path: '/landing'
      fullPath: '/dashboard/landing'
      preLoaderRoute: typeof DashboardLandingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/invites': {
      id: '/dashboard/invites'
      path: '/invites'
      fullPath: '/dashboard/invites'
      preLoaderRoute: typeof DashboardInvitesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/events': {
      id: '/dashboard/events'
      path: '/events'
      fullPath: '/dashboard/events'
      preLoaderRoute: typeof DashboardEventsRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ceremonies': {
      id: '/dashboard/ceremonies'
      path: '/ceremonies'
      fullPath: '/dashboard/ceremonies'
      preLoaderRoute: typeof DashboardCeremoniesRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/weddings': {
      id: '/admin/weddings'
      path: '/weddings'
      fullPath: '/admin/weddings'
      preLoaderRoute: typeof AdminWeddingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/emails': {
      id: '/admin/emails'
      path: '/emails'
      fullPath: '/admin/emails'
      preLoaderRoute: typeof AdminEmailsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/activity': {
      id: '/admin/activity'
      path: '/activity'
      fullPath: '/admin/activity'
      preLoaderRoute: typeof AdminActivityRouteImport
      parentRoute: typeof AdminRoute
    }
    '/dashboard/guests/': {
      id: '/dashboard/guests/'
      path: '/guests'
      fullPath: '/dashboard/guests/'
      preLoaderRoute: typeof DashboardGuestsIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/guests/new': {
      id: '/dashboard/guests/new'
      path: '/guests/new'
      fullPath: '/dashboard/guests/new'
      preLoaderRoute: typeof DashboardGuestsNewRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/ceremonies/$id': {
      id: '/dashboard/ceremonies/$id'
      path: '/$id'
      fullPath: '/dashboard/ceremonies/$id'
      preLoaderRoute: typeof DashboardCeremoniesIdRouteImport
      parentRoute: typeof DashboardCeremoniesRoute
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/paystack': {
      id: '/api/public/webhooks/paystack'
      path: '/api/public/webhooks/paystack'
      fullPath: '/api/public/webhooks/paystack'
      preLoaderRoute: typeof ApiPublicWebhooksPaystackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminActivityRoute: typeof AdminActivityRoute
  AdminEmailsRoute: typeof AdminEmailsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminWeddingsRoute: typeof AdminWeddingsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminActivityRoute: AdminActivityRoute,
  AdminEmailsRoute: AdminEmailsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminWeddingsRoute: AdminWeddingsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface DashboardCeremoniesRouteChildren {
  DashboardCeremoniesIdRoute: typeof DashboardCeremoniesIdRoute
}

const DashboardCeremoniesRouteChildren: DashboardCeremoniesRouteChildren = {
  DashboardCeremoniesIdRoute: DashboardCeremoniesIdRoute,
}

const DashboardCeremoniesRouteWithChildren =
  DashboardCeremoniesRoute._addFileChildren(DashboardCeremoniesRouteChildren)

interface DashboardRouteChildren {
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardCeremoniesRoute: typeof DashboardCeremoniesRouteWithChildren
  DashboardEventsRoute: typeof DashboardEventsRoute
  DashboardInvitesRoute: typeof DashboardInvitesRoute
  DashboardLandingRoute: typeof DashboardLandingRoute
  DashboardPreviewRoute: typeof DashboardPreviewRoute
  DashboardShareRoute: typeof DashboardShareRoute
  DashboardStatsRoute: typeof DashboardStatsRoute
  DashboardVueRoute: typeof DashboardVueRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardGuestsNewRoute: typeof DashboardGuestsNewRoute
  DashboardGuestsIndexRoute: typeof DashboardGuestsIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardCeremoniesRoute: DashboardCeremoniesRouteWithChildren,
  DashboardEventsRoute: DashboardEventsRoute,
  DashboardInvitesRoute: DashboardInvitesRoute,
  DashboardLandingRoute: DashboardLandingRoute,
  DashboardPreviewRoute: DashboardPreviewRoute,
  DashboardShareRoute: DashboardShareRoute,
  DashboardStatsRoute: DashboardStatsRoute,
  DashboardVueRoute: DashboardVueRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardGuestsNewRoute: DashboardGuestsNewRoute,
  DashboardGuestsIndexRoute: DashboardGuestsIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface OnboardingRouteChildren {
  OnboardingDatesRoute: typeof OnboardingDatesRoute
  OnboardingEvenementRoute: typeof OnboardingEvenementRoute
  OnboardingPrenomsRoute: typeof OnboardingPrenomsRoute
  OnboardingThemeRoute: typeof OnboardingThemeRoute
}

const OnboardingRouteChildren: OnboardingRouteChildren = {
  OnboardingDatesRoute: OnboardingDatesRoute,
  OnboardingEvenementRoute: OnboardingEvenementRoute,
  OnboardingPrenomsRoute: OnboardingPrenomsRoute,
  OnboardingThemeRoute: OnboardingThemeRoute,
}

const OnboardingRouteWithChildren = OnboardingRoute._addFileChildren(
  OnboardingRouteChildren,
)

interface PublishRouteChildren {
  PublishSuccessRoute: typeof PublishSuccessRoute
}

const PublishRouteChildren: PublishRouteChildren = {
  PublishSuccessRoute: PublishSuccessRoute,
}

const PublishRouteWithChildren =
  PublishRoute._addFileChildren(PublishRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BlogRoute: BlogRoute,
  CommentCaMarcheRoute: CommentCaMarcheRoute,
  DashboardRoute: DashboardRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  InvitationRoute: InvitationRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRouteWithChildren,
  PolitiqueDeConfidentialiteRoute: PolitiqueDeConfidentialiteRoute,
  PublishRoute: PublishRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TemoignagesRoute: TemoignagesRoute,
  TermesEtConditionsRoute: TermesEtConditionsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  AppProfileRoute: AppProfileRoute,
  ESlugRoute: ESlugRoute,
  ThemeThumbSlugRoute: ThemeThumbSlugRoute,
  ApiPublicWebhooksPaystackRoute: ApiPublicWebhooksPaystackRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
